version: "3.2"
services:
  web:
    image: nginx:latest
    ports:
      #TODO: just map 80 to 80 and 443 to 443...
      - "8080:443"
    volumes:
      - ./frontend:/frontend
      - ./nginxLogs/access.log:/var/log/nginx/access.log
      - ./nginxLogs/error.log:/var/log/nginx/error.log
      - ./nginxConfFiles/nginx.conf:/etc/nginx/nginx.conf
      - ./nginxConfFiles/sites-available:/etc/nginx/sites-available
      - ./nginxConfFiles/sites-enabled:/etc/nginx/sites-enabled
      - ./nginxConfFiles/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./nginxConfFiles/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    links:
      - php
    networks:
      - frontend
      - backend
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  php:
    build: ./php
    volumes:
      - ./frontend:/frontend
    networks:
      - backend
  mysql:
    image: mysql:latest
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./database:/var/lib/mysql
networks:
  frontend:
  backend: